= Java EE Moving to an Open Source Foundation

In case you haven’t seen the blog post, https://blogs.oracle.com/theaquarium/opening-up-java-ee[Opening Up Java EE], Oracle has announced that they are moving Java EE to an open source foundation in order to make it more agile and responsive to industry and technology demands. Oracle has been listening to the Java EE community, and has come up with a promising solution.

You may be asking *“How does this impact Eclipse MicroProfile as a project and as a community”?*

As a project, MicroProfile was founded as a means to collaborate on microservices specifications within an open source community and to accelerate the adoption of microservices for enterprise Java developers. We have been doing this for over a year with the launch of MicroProfile 1.0, the recent release of MicroProfile 1.1 and the up-coming MicroProfile 1.2. We should expect the contribution of Java EE to an open community to make it faster and easier in the future for MicroProfile technology to extend Java EE - through more common community practices, governance and shared ownership. In the meantime, we plan to continue the development of new ideas and new frameworks that can help developers on a day-to-day basis, and execute on MicroProfile 1.2 and beyond.

As a community, a vast majority of us have our roots in Java EE. MicroProfile 1.0, for example, includes three Java EE-related JSRs. Some of us are JCP EC members. Some of us work for Java EE vendors. Some MicroProfile vendors integrate MicroProfile into existing Java EE application servers. We all love to develop code with Java EE and build innovative applications. At the same time, we have grown our own identity as a community that has been collaborating in an open source manner with a faster, lighter-weight process to foster innovation.

How do we normalize these two different but related communities? Well, that’s up to us! Our overall goals do not change. The Java EE community has focused on standards, while MicroProfile has focused on rapid collaborative innovation. Both want to facilitate user choice through multiple implementations and to be agile and more responsive to developers. There are various ways these goals can align as we move forward. Let’s take our time, think it through, have some great conversations, make decisions, and execute. What an awesome opportunity.
