= Eclipse MicroProfile welcomes Oracle to its community

Oracle has officially joined the group of prestigious member organizations that are supporting the http://microprofile.io[Eclipse MicroProfile] initiative. Oracle has been maintaining and running the Java EE standard for over fifteen years and recently announced that it was transitioning Oracle Java EE technologies to The Eclipse Foundation project called https://blogs.oracle.com/theaquarium/ee4j-eclipse-enterprise-for-java[EE4J].

Eclipse MicroProfile and EE4J both promote Enterprise Java in the areas of microservices, server-side and cloud-native applications. The Java EE community has focused on standards, while MicroProfile has focused on rapid collaborative innovation. Both want to facilitate user choice through multiple implementations and to be agile and more responsive to developers. There are various ways these goals can align as both open source projects move forward.

There is a lot of synergy between Eclipse MicroProfile and EE4J and customers will continue to benefit from their respective development. Currently, Oracle and EE4J member organizations are busy setting up the EE4J Eclipse project to insure its continued success, which will, in turn, help drive the alignment of EE4J and MicroProfile.  We welcome Oracle to our MicroProfile community and look forward to working with them.
