= Eclipse MicroProfile welcomes Oracle to its community

Oracle has officially joined the group of prestigious member organizations that are supporting the http://microprofile.io[Eclipse MicroProfile] initiative. Oracle has been maintaining and running the Java EE standard for over fifteen years and recently announced that it was moving Java EE under The Eclipse Foundation project called https://blogs.oracle.com/theaquarium/ee4j-eclipse-enterprise-for-java[EE4J].

Eclipse MicroProfile and EE4J both deal with the use of Enterprise Java, the former as a community-driven open source specification for enterprise Java microservices and the latter as a standard for running enterprise applications. The Java EE community has focused on standards, while MicroProfile has focused on rapid collaborative innovation. Both want to facilitate user choice through multiple implementations and to be agile and more responsive to developers. There are various ways these goals can align as both open source projects move forward.

There is a lot of synergy between Eclipse MicroProfile and EE4J and customers will continue to benefit from their respective development. Currently, Oracle and EE4J member organizations are busy setting up the EE4J Eclipse project to insure the continued success of the standard.  We welcome Oracle to our MicroProfile community and look forward to working with them.
