= Announcing MicroProfile 1.0

We would like to officially announce MicroProfile 1.0! In only three months, as promised, we have gone from an https://www.infoq.com/news/2016/07/java-ee-microprofile[announced collaboration] to delivering multiple implementations. We have agreed on a base set of features that defines solid and stable roots on which to grow, grown to 6 implementations, and have added multiple member organizations and http://microprofile.io/contributors[contributors].

== What’s New in this Release?

Everything :-)

More specifically, JAX-RS, CDI, JSON-P support, and samples.

== Getting Started

To get started with MicroProfile, clone the https://github.com/microprofile/microprofile-conference[conference app] or https://github.com/microprofile/microprofile-samples[samples] and run them on one of the 6 implementations from Red Hat (http://wildfly-swarm.io[WildFly Swarm]), IBM (https://developer.ibm.com/wasdev/blog/2016/09/16/new-release-websphere-liberty-16-0-0-3/[Liberty Profile]), Tomitribe (Apache https://tomitribe.io/[TomEE]), Payara (http://www.payara.fish/payara_micro[Payara Micro]), and https://github.com/hammock-project/hammock/wiki/Microprofile[Hammock].


== What’s Next for MicroProfile?

From a technology perspective, you tell us. MicroProfile 1.0 is intentionally feature-constrained so that a broader community can define its roadmap. We have a simple poll that you can take 	on the bottom of the microprofile.io http://microprofile.io/[front page] that will provide us all helpful insights, though we obviously have our own thoughts on where we’d like to go next, including such things as asynchronous, reactive microservices, security, service discovery and some components of the NetflixOSS stack.

From a project perspective, https://docs.google.com/document/d/1THnk3n7Q2n9ml0F2jkOgW3qmcCyMfo7y95w2krL2Dig/edit#heading=h.e7lwedyyvju[we plan] to move MicroProfile to a foundation where we collectively own its future. A foundation provides established business and technical processes like governance and membership guidelines, legal and marketing functions, software build infrastructure, and so on.

Stay tuned. Better yet, https://groups.google.com/forum/#!forum/microprofile[stay  in the know] and also check out the the roadmap section of the https://docs.google.com/presentation/d/13zHkdv_ri5Twcq4emJ9lnEH7t9gtkb65B5-kY-u0yKM[MicroProfile presentation]. Join other community members to learn more about MicroProfile 1.0 and its roadmap at the http://microprofilelunch.com/JavaOne[MicroProfile panel luncheon] during JavaOne on Thursday, September 22nd. 

== Additional Resources 

http://microprofile.io[MicroProfile.io] +
http://microprofile.io/faq[MicroProfile FAQ] +
https://docs.google.com/presentation/d/13zHkdv_ri5Twcq4emJ9lnEH7t9gtkb65B5-kY-u0yKM[MicroProfile Presentation] +
https://github.com/microprofile[MicroProfile on GitHub]
